In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,5,7])
print("this is a numpy array",arr1)
print("the shape of this array is ", arr1.shape)

#converting the numpy array from one dimension to two dimension
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)
print("New array and its shape is ", arr2, arr2.shape)
arr3 = np.array([[1,2,3,4,5]])
print(arr3, arr3.shape)

this is a numpy array [1 2 3 4 5 7]
the shape of this array is  (6,)
New array and its shape is  [1 2 3 4 5] (5,)
[[1 2 3 4 5]] (1, 5)


In [11]:
#to create numpy arrays of a range
np.arange(0,10,2).reshape(5,1)
arr4 = np.arange(0,10,2)
arr4 = arr4.reshape(5,1) #arr.reshape(rows,cols) returns another new reshaped array which is to be changed. 
print(arr4)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [16]:
#create array with all ones
print(np.ones((3,4))) #np.ones(rows, cols)

#create array with all zeroes
np.zeros((3,4))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
###Numpy vectorized operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([7,8,9,10,11])

print("Element wise addition", arr1+arr2)
print("Element wise multilication", arr1*arr2)
print("Element wise subtraction", arr1-arr2)
print("Element wise division", arr1/arr2)
 

Element wise addition [ 8 10 12 14 16]
Element wise multilication [ 7 16 27 40 55]
Element wise subtraction [-6 -6 -6 -6 -6]
Element wise division [0.14285714 0.25       0.33333333 0.4        0.45454545]


In [20]:
arr4 = np.array([1,2,3,4,5])
print("Element wise square root", np.sqrt(arr4))

print("Element wise exponential", np.exp(arr4))
#same way we can do SINE and LOG 

Element wise square root [1.         1.41421356 1.73205081 2.         2.23606798]
Element wise exponential [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [29]:
#Array sliciing and indexing
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)
print("first element in the 2d array is :", arr[0][0])

print("specific slicing of array ", arr[1: , 2:])

print("again doing the same ", arr[0:2 , 2:])


print()
print("Again doing the same but for my practice", arr[1: , 1:3])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
first element in the 2d array is : 1
specific slicing of array  [[ 7  8]
 [11 12]]
again doing the same  [[3 4]
 [7 8]]

Again doing the same but for my practice [[ 6  7]
 [10 11]]


In [31]:
## Modifying elements
arr[0][0] = 100
arr

print("modifying an entire array")
arr[1:] = 100 #all elements after 1st row have values as 100
print(arr)

modifying an entire column
[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [35]:
# Statistical concept Normalization 
# converting your data to have a mean of 0 and a standard deviation of 1

arrr = np.array([1,2,3,4,5])
means = np.mean(arrr)
stand = np.std(arrr)

normalizeddata = (arrr - means) / stand
print(normalizeddata, np.mean(normalizeddata))
#other functions np.var , np.median  

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356] 0.0


In [37]:
# Logical statements 
data = np.array([1,2,3,4,5,6,7,8,9])
print(data > 5) #returns an array which checks the condition for each element in data   

#specific retrieval of data
print(data[data > 3])

[False False False False False  True  True  True  True]
[4 5 6 7 8 9]
